volumes:
  - /home/ec2-user/public/uploads:/rails/public/uploads
  - /home/ec2-user/public/assets:/rails/public/assets

servers:
  web:
    hosts:
      # dental-kamal-web-prod
      - 18.130.39.133
    cmd:
      bash -c "bin/rails s -p 3000 -b 0.0.0.0"

accessories:
  redis:
    image: redis:latest
    # dental-kamal-web-prod
    host: 18.130.39.133
    port: 6379
    cmd: "redis-server --requirepass <%= Dotenv.parse('.env.prod').fetch('REDIS_URL').match(/\/\/:(.*)@/)[1] %>"
    directories:
      - /var/lib/redis:/data

env:
  clear:
    PORT: 3000
    RAILS_ENV: production
    RAILS_MAX_THREADS: 5
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_URL
    - REDIS_URL

# http://18.175.25.24:8080
traefik:
  options:
    publish:
      - 8080:8080
  args:
    accesslog: true
    accesslog.format: json
    api.dashboard: true
    api.insecure: true
